---
- name: Include OS Specific Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Extra Packages
  package:
    name: "{{ common_package_list }}"
    state: present

- name: Create User Groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
    state: "{{ item.state }}"
  with_items: "{{ common_groups }}"

- name: Create User Accounts
  user:
    name: "{{ item.name }}"
    uid: "{{ item.id }}"
    group: "{{ item.id }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
  with_items: "{{ common_users }}"

- name: Add Authorized Key
  authorized_key:
    user: "{{ item.name }}"
    state: "{{ item.state }}"
    key: "{{ item.ssh_key }}"
  with_items: "{{ common_users }}"

- name: Add groups to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ item.name }}
    line: "%{{ item.name }} {{ item.permission }}"
    # line: "%{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    state: "{{ item.state }}"
    mode: 0440
    create: yes
    validate: "visudo -cf %s"
  with_items: "{{ common_sudoers }}"
