---
- name: Converge
  hosts: all
  vars:
    common_groups:
      - {name: sysadmin, id: 5000, state: present}
    common_users:
      - name: bhope
        id: 5000
        group: sysadmin
        state: present
        shell: /bin/zsh}
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDND2nHkjkKw7YV5hS310ALmT+IUYuZRCroVFzYPE0c2XT5tgrvdEYoI0G+NWG1kfv3iGWT6tW03C8PC9e8imEFG7w778RaDI4FUDt9FpVnRa68yGEn+/+/YdV3KyXiQQsZQrsswEoYsBJqWiBHYsCKYw56kgsHlZ6BM6WDAvbyx9/1IHvyYGgXWbsm6qJ/m6tZD7+wzliJtu8IqjTrfWlHfeCT9NOng6LzgGC/rUdiD7H5f44TILVEFIl4mAgNcTdVYOgvTnEwtiuCkf6/7p4DWLsjHKNU9zl7ZpAY3pjwzNeqUKRwz0r39R6+97Nut4V0HY0TerObuRv1s+WJsN1T8mgKb1d/6yQazojSCspyWmBaYPXcQfW4yvUV9DedDWCMaYE8Yf+m6+mj9LsfOdWP+Dy02Ul9UyNjPfNrKwAmvpDGFQsFAtPYnEURSCSbO6BLoHyIR87YY8VO/1XIO86EEC4Q62AUHuY/6RpuTOFVWxb5wP2EtM9JrgbIiOdGMgd5kcf1E8YPv+a7IpCWWbpasGb5X82P77rVd3FxWT9fnIVDxF4D//JjdLLRmYSlsw/04IRQVaYyD4NZICFZK8w9BgsuUTIG5+r6q82ytNvhAyZiAEck2BOmFdA+Etts6kWO9Civ3DzfLqykXgk03fr6YdZ6+jGQoKLpVB8UM3QPRw== cardno:000607843859
    common_sudoers:
      - {name: sysadmin, state: present, permission: "ALL=(ALL) NOPASSWD:ALL"}
    common_hostname: common_test
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
